name: Publish to Poetry

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install

    - uses: actions/setup-setup-dotnet@v1
    - uses: actions/setup-gitversion@v1.0.0
      with:
        gitversion-version: 5.1.1
    - run: GitVersion

    #- name: Update poetry Buildnumber
    #  run: poetry version ${{ steps.buildnumber.outputs.build_number }}
      
    - name: Build and publish to pypi
      uses: JRubics/poetry-publish@v1
      with:
        pypi_token: ${{ secrets.PYPI_TOKEN }}
